# Generated by Django 2.1.3 on 2018-11-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181124_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('classname', 'project')},
        ),
    ]
