# Generated by Django 2.1.3 on 2018-11-25 12:20

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181124_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('used_algorithm', models.CharField(choices=[('nb', 'Naive Bayes'), ('svm', 'Support Vector Machine'), ('mlp', 'Multi Layer Perceprton')], default=('nb', 'Naive Bayes'), max_length=100)),
                ('parameters', picklefield.fields.PickledObjectField(editable=False)),
                ('hyperparameters', picklefield.fields.PickledObjectField(editable=False)),
                ('model_status', models.IntegerField(choices=[(0, 'Not trained'), (1, 'Training'), (2, 'Trained')], default=0)),
                ('validation_results', picklefield.fields.PickledObjectField(editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='label_probability',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Classifier',
        ),
    ]
