# Generated by Django 2.1.3 on 2018-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181125_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiermodel',
            name='uuid',
        ),
        migrations.AddField(
            model_name='classifiermodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
