# Generated by Django 2.1.3 on 2018-11-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181125_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiermodel',
            old_name='hyperparameters',
            new_name='estimator',
        ),
        migrations.RemoveField(
            model_name='classifiermodel',
            name='parameters',
        ),
    ]
